### ISSUE TITLE
Release checklist for version 1.8.0

### ISSUE THREAD

**Issue by leslie-huang** [rstudio/leaflet.providers#17]
- [x] Create branch labeled v1.8.0-rc
- [x] Change DESCRIPTION and NEWS on this branch to match the desired version for CRAN
- [x] Commit and push to the RC branch
- [x] Clean pkg dir to remove any extraneous files
- [x] Build your package from the command line
  - [x] using PATH=$PATH:/Applications/RStudio.app/Contents/MacOS/pandoc R CMD build leaflet.providers
    - [x] test the built package with R CMD check --as-cran
    - [x] install the built package R CMD install leaflet.providers_1.8.0.tar.gz
  - [x] using devtools::build
    - [x] test the built package with R CMD check --as-cran
    - [x] install the built package R CMD install leaflet.providers_1.8.0.tar.gz
- [x] devtools::check()
- [x] devtools::release() but don't send to CRAN
- [x] Check Windows
  - [x] devtools::check_win_devel()
  - [x] devtools::check_win_release()
  - [x] devtools::check_win_oldrelease()
- [x] Check rhub
  - [x] linux/R-devel
  - [x] windows/R-devel
  - [x] linux/R-release
- [x] Check CRAN Policies
- [x] Submit to CRAN
  - [x] Update CRAN comments
  - [x] devtools::check()
  - [x] devtools::release()
- [x] After CRAN acceptance
  - [x] Merge RC branch into master
  - [x] Tag merged commit
  - [x] Make GitHub release on merged commit
